name: usedesk_example
description: Demonstrates how to use the usedesk plugin.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  usedesk:
    path: ../
  shared_preferences: ^2.0.13

  cupertino_icons: ^1.0.4
  file_picker: ^4.4.0
  flutter_chat_ui: ^1.5.5
  image_picker: ^0.8.4+9
  intl: ^0.17.0
  open_file: ^3.2.1
  uuid: ^3.0.5
  url_launcher: ^6.0.20
  package_info_plus: ^1.4.0
  path_provider: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

dependency_overrides:
  # issue https://github.com/bluefireteam/photo_view/issues/489 d 
  photo_view:
      git: https://github.com/bluefireteam/photo_view.git

flutter:
  uses-material-design: true
