name: usedesk
description: Pure dart SDK implementation of usedesk.com service. Includes client realtime chat
repository: https://github.com/ScerIO/usedesk.dart
issue_tracker: https://github.com/ScerIO/usedesk.dart/issues
version: 0.7.0

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  socket_io_client: ^2.0.0
  mime: ^1.0.2
  http: ^0.13.5
  http_parser: ^4.0.1
  filesize: ^2.0.1
  path: ^1.8.1

dev_dependencies:
  lints: ^2.0.0
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  json_serializable: ^6.2.0
  analyzer: ^4.6.0
